import { useSyncExternalStore } from "react";
const en = {
  aspectFilter: "Evidence aspect",
  allAspects: "All aspects",
  typeFilter: "Information type",
  allTypes: "All types",
  usageFilter: "Reference use",
  allUsage: "All use states",
  aspectContent: "Content",
  aspectApplicability: "Applicability",
  aspectDecision: "Decision",
  aspectExploration: "Exploration",
  typeKnowledge: "Knowledge",
  typeIdea: "Idea",
  typeReference: "Reference",
  typeRaw: "Source material",
  typeMoc: "Map of content",
  usageViewed: "Viewed",
  usageMentioned: "Mentioned",
  usageUsed: "Used",
  usageAdopted: "Adopted",
  usageExcluded: "Excluded",
  usageDiscovered: "Discovered only",
  newReferences: "New references are ready",
  showNewReferences: "Show new references",
  referencePages: "Reference pages",
  previousPage: "Previous page",
  nextPage: "Next page",
  page: "Page",
  documents: "documents",
  wholeDocument: "Whole document",
  assumptionOpen: "Open assumption",
  assumptionConfirmed: "Confirmed assumption",
  assumptionRejected: "Rejected assumption",
  assumptionSuperseded: "Superseded assumption",
  selectMention: "Select mention",
  insertSelectedMentions: "Insert selected mentions",
  selectedMentions: "Selected mentions",

  title: "Work preview",
  evidence: "Evidence and assumptions",
  generate: "Generate preview",
  investigate: "Check references",
  loading: "Loading preview…",
  generating: "Preparing preview and evidence…",
  failed: "Preview generation failed. Your last preview is preserved.",
  noResults: "No suitable local evidence found",
  notNeeded: "No search needed",
  results: "Exact local evidence retrieved",
  changed: "Context changed; earlier results are historical",
  optionalFailed: "Optional investigation failed; you can keep talking",
  optionalRunning: "Checking references in the background…",
  optionalDone: "Reference check complete",
  retry: "Retry",
  historical: "Historical preview · read only",
  current: "Current",
  generated: "Generated",
  edited: "Edited",
  restored: "Restored",
  reconciled: "Reconciled",
  version: "Version",
  versions: "Preview versions",
  compare: "Compare versions",
  left: "Earlier version",
  right: "Later version",
  restore: "Restore as new",
  comparison: "Version comparison",
  changedField: "Changed",
  unchanged: "Unchanged",
  added: "Added",
  removed: "Removed",
  description: "Description",
  background: "Background",
  goal: "Goal",
  scope: "Scope",
  nonGoals: "Non-goals",
  constraints: "Constraints",
  completionCriteria: "Completion criteria",
  initialApproach: "Initial approach",
  assumptions: "Assumptions",
  user_context: "User context",
  source: "Source evidence",
  model_inference: "Model inference",
  empty: "Not specified",
  edit: "Edit preview",
  save: "Save preview",
  cancel: "Cancel edit",
  apply: "Apply to Task",
  saved: "Preview saved",
  applied: "Preview applied",
  queued: "A newer preview is available. Your edits are preserved.",
  dirty: "Save or cancel your edits before changing versions.",
  references: "References",
  search: "Search references",
  filter: "Reference status",
  sort: "Reference order",
  all: "All statuses",
  titleSort: "Title",
  stable: "Reading order",
  currentStatus: "Current",
  historicalStatus: "Historical",
  unverified: "Unverified",
  deferred: "Deferred",
  rejected: "Rejected",
  emptyReferences: "No matching references",
  critical: "Important finding",
  supporting: "Supporting evidence",
  ancillary: "Related background",
  use: "Mark used",
  exclude: "Exclude",
  readFailed: "Could not open this exact source version.",
  close: "Close reference",
  navigation: "Reference navigation",
  back: "Back",
  forward: "Forward",
  previous: "Previous reference",
  next: "Next reference",
  loadingReference: "Loading reference…",
  sourceVersion: "Source version",
  mentions: "Reference mentions",
  removeMention: "Remove mention",
  mentionHint: "Type @ to insert a document or section without sending",
  actionFailed: "The action could not be completed. Your edits are preserved.",
};
const ko: typeof en = {
  aspectFilter: "근거 관점",
  allAspects: "모든 관점",
  typeFilter: "정보 유형",
  allTypes: "모든 유형",
  usageFilter: "참조 사용",
  allUsage: "모든 사용 상태",
  aspectContent: "내용",
  aspectApplicability: "적용 조건",
  aspectDecision: "결정",
  aspectExploration: "탐색",
  typeKnowledge: "Knowledge",
  typeIdea: "Idea",
  typeReference: "참조",
  typeRaw: "원본 자료",
  typeMoc: "목차",
  usageViewed: "열람됨",
  usageMentioned: "멘션됨",
  usageUsed: "사용됨",
  usageAdopted: "채택됨",
  usageExcluded: "제외됨",
  usageDiscovered: "발견만 됨",
  newReferences: "새 참조가 준비되었습니다",
  showNewReferences: "새 참조 보기",
  referencePages: "참조 페이지",
  previousPage: "이전 페이지",
  nextPage: "다음 페이지",
  page: "페이지",
  documents: "개 문서",
  wholeDocument: "문서 전체",
  assumptionOpen: "미확정 가정",
  assumptionConfirmed: "확인된 가정",
  assumptionRejected: "기각된 가정",
  assumptionSuperseded: "대체된 가정",
  selectMention: "멘션 선택",
  insertSelectedMentions: "선택한 멘션 삽입",
  selectedMentions: "선택한 멘션",

  title: "작업 초안",
  evidence: "근거와 가정",
  generate: "초안 생성",
  investigate: "참조 확인",
  loading: "초안 불러오는 중…",
  generating: "초안과 근거 준비 중…",
  failed: "초안 생성에 실패했습니다. 이전 초안은 보존됩니다.",
  noResults: "적합한 로컬 근거를 찾지 못했습니다",
  notNeeded: "검색이 필요하지 않습니다",
  results: "정확한 로컬 근거를 확인했습니다",
  changed: "맥락이 바뀌어 이전 결과를 이력으로 보관합니다",
  optionalFailed: "선택적 조사에 실패했습니다. 대화는 계속할 수 있습니다",
  optionalRunning: "백그라운드에서 참조 확인 중…",
  optionalDone: "참조 확인 완료",
  retry: "재시도",
  historical: "이전 초안 · 읽기 전용",
  current: "현재",
  generated: "생성됨",
  edited: "편집됨",
  restored: "복원됨",
  reconciled: "조정됨",
  version: "버전",
  versions: "초안 버전",
  compare: "버전 비교",
  left: "이전 버전",
  right: "다음 버전",
  restore: "새 버전으로 복원",
  comparison: "버전 비교 결과",
  changedField: "변경됨",
  unchanged: "변경 없음",
  added: "추가됨",
  removed: "삭제됨",
  description: "설명",
  background: "배경",
  goal: "목표",
  scope: "범위",
  nonGoals: "범위 제외",
  constraints: "제약",
  completionCriteria: "완료 기준",
  initialApproach: "초기 접근법",
  assumptions: "가정",
  user_context: "사용자 맥락",
  source: "출처 근거",
  model_inference: "모델 추론",
  empty: "지정되지 않음",
  edit: "초안 편집",
  save: "초안 저장",
  cancel: "편집 취소",
  apply: "Task에 적용",
  saved: "초안을 저장했습니다",
  applied: "초안을 적용했습니다",
  queued: "새 초안이 있습니다. 사용자 편집은 보존됩니다.",
  dirty: "버전을 바꾸기 전에 편집을 저장하거나 취소하세요.",
  references: "참조",
  search: "참조 검색",
  filter: "참조 상태",
  sort: "참조 정렬",
  all: "모든 상태",
  titleSort: "제목",
  stable: "읽던 순서",
  currentStatus: "현재",
  historicalStatus: "이전",
  unverified: "미검증",
  deferred: "보류",
  rejected: "기각",
  emptyReferences: "일치하는 참조가 없습니다",
  critical: "중요 발견",
  supporting: "보충 근거",
  ancillary: "관련 배경",
  use: "사용 표시",
  exclude: "제외",
  readFailed: "이 출처의 정확한 버전을 열지 못했습니다.",
  close: "참조 닫기",
  navigation: "참조 탐색",
  back: "뒤로",
  forward: "앞으로",
  previous: "이전 참조",
  next: "다음 참조",
  loadingReference: "참조 불러오는 중…",
  sourceVersion: "출처 버전",
  mentions: "참조 멘션",
  removeMention: "멘션 제거",
  mentionHint: "@로 문서나 절을 입력합니다. 자동 전송되지 않습니다",
  actionFailed: "작업을 완료하지 못했습니다. 사용자 편집은 보존됩니다.",
};
const subscribe = (changed: () => void) => {
  const observer = new MutationObserver(changed);
  observer.observe(document.documentElement, {
    attributes: true,
    attributeFilter: ["lang"],
  });
  return () => observer.disconnect();
};
export const useReferenceWorkbenchText = () =>
  useSyncExternalStore(
    subscribe,
    () => (document.documentElement.lang.startsWith("ko") ? ko : en),
    () => en,
  );
