import { useSyncExternalStore } from "react";

const en = {
  attachImage: "Attach image",
  removeImage: "Remove image",
  imageHint: "Paste an image or choose a file · PNG, JPEG, GIF, WebP · up to 10 MB",
  imageError: "Choose a PNG, JPEG, GIF or WebP image up to 10 MB.",
  imageReadError: "Could not read the image. Try selecting it again.",
  imageCapture: "Image capture",
  attachedImage: "Attached image",
  workspace: "Local workspace",
  refined: "Refined - Revision",
  workStatus: "Work status",
  previewTab: "Preview",
  focus: "Focus active work",
  showAllWork: "Show all work",
  subtask: "Subtask",
  subtasks: "Subtasks",
  parentTask: "Parent Task",
  siblingTasks: "Sibling Tasks",
  boundaryReason: "Why a Subtask is needed",
  boundaryContext: "Task boundaries",
  autoPublishFailure: "Automatic publication is pending; reopen this Task to retry",
  subtaskHint: "Each Subtask completion updates and publishes the parent Knowledge revision. The parent closes when all Subtasks finish.",
  vaultStatus: "Local · your vault",
  entryMode: "Entry mode",
  entryLabel: "Workbench entry",
  resume: "Resume",
  ready: "Task",
  inProgress: "In progress",
  completed: "Completed",
  heading: "Your workbench",
  capture: "Capture a thought",
  task: "Register as a Task",
  placeholder: "What would you like to keep or work on?",
  save: "Save",
  active: "Active tasks",
  refining: "Refining",
  categories: "All work",
  inbox: "Inbox",
  inboxHint: "Thoughts to come back to",
  noInbox: "Capture a thought to get started.",
  refiningHint: "Shape ideas into clear work",
  refinedTasks: "Refined Tasks",
  refinedTasksHint: "Choose your next piece of work",
  noReadyTasks: "Tasks will appear here when registered or refined.",
  empty: "Nothing here yet. Capture a thought or register a Task.",
  retry: "Try again",
  open: "Open Task",
  refine: "Refine",
  worklog: "Work Log",
  work: "Work",
  detailsTab: "Details",
  reviewTab: "Review",
  worklogEntry: "Work Log entry",
  imageSummary: "AI image summary",
  summarizeImage: "Summarize image · Korean + English",
  imageSummaryPending: "Generating Korean and English summaries in the AI queue…",
  imageSummaryFailed: "Image summary was not completed. Retry here or in the AI queue.",
  noWorkLog: "Record the first piece of work when you are ready.",
  goalMissing: "Add an intended outcome in Details to give this work a clear goal.",
  start: "Start work",
  complete: "Complete Task",
  addCompletionEvidence: "Add completion evidence",
  reviewCompletion: "Review completion",
  reopen: "Reopen Task",
  readiness: "Readiness",
  readinessOutcome: "Outcome",
  readinessScope: "Scope",
  readinessCriteria: "Validation criteria",
  readinessPrerequisites: "Prerequisites",
  statusResolved: "Resolved",
  statusMissing: "Missing",
  statusNotApplicable: "Not applicable",
  relationships: "Connections",
  connectionDetails: "Connection details",
  completion: "Completion",
  knowledge: "Knowledge",
  review: "Conflict review",
  runReview: "Run review",
  retryReview: "Retry review",
  cancel: "Cancel",
  currentReviewResult: "Current result",
  reviewClear: "Clear",
  reviewFindings: "Findings",
  reviewInsufficient: "Insufficient evidence",
  reviewQueued: "Queued",
  reviewRunning: "Running",
  reviewFailed: "Failed",
  reviewCancelled: "Cancelled",
  reviewStale: "Stale",
  reviewAttempts: "Review attempts",
  reviewAttempt: "Attempt",
  add: "Add",
  saveChanges: "Save changes",
  nonblocking: "Review is advisory. You can continue working.",
  proposals: "Proposals",
  previewContext: "Related context",
  previewReturn: "Back to preview",
  previewCategory: "Category",
  previewNote: "Note",
  previewTitle: "Proposed result",
  previewUnapplied: "Preview · not applied",
  previewEmpty: "Your proposed result will appear here after the assistant responds.",
  previewGenerating: "Updating the preview in the AI queue…",
  previewQueueRecovery: "The preview is unavailable. Retry it in the AI queue or send another message. Your chat is saved.",
  previewNewTask: "Refine this item",
  splitTask: "Split into a subtask",
  originalCapture: "Original capture",
  previewTaskChange: "Task changes",
  previewProblem: "Problem changes",
  previewConnection: "Problem connection",
  previewApplied: "Applied. The current work has been updated.",
  previewRejected: "Proposal dismissed. Your current work is retained.",
  previewFinishEdit: "View preview",
  closeRefinement: "Close refinement",
  backToTask: "Back to Task",

  problem: "Problem context",
  publish: "Publish approved draft",
  taskDetails: "Task details",
  closeTaskDetail: "Close Task detail",
  back: "Back to Workbench",
  title: "Title",
  detail: "Detail",
  outcome: "Outcome",
  scope: "Scope",
  nonGoals: "Non-goals",
  criteria: "Validation criteria",
  checklist: "Checklist",
  checklistItem: "Checklist item",
  showCompleted: "Show completed",
  showAllChecklist: "Show all items",
  collapseChecklist: "Show fewer items",
  hideCompleted: "Hide completed",
  decisions: "Decisions",
  decisionEntry: "Decision",
  newProblemStatement: "New Problem statement",
  newProblemPlaceholder: "Describe a Problem to link",
  createAndLinkProblem: "Create and link Problem",
  problemRevisionStatement: "Problem revision statement",
  problemRevisionPlaceholder: "Revise the linked Problem",
  reviseProblem: "Revise Problem",
  problemId: "Problem ID",
  problemRevision: "Problem revision",
  linkProblem: "Link Problem",
  relatedTaskId: "Related Task ID",
  taskId: "Task ID",
  relationshipKind: "Relationship kind",
  related: "Related",
  prerequisite: "Prerequisite",
  splitFrom: "Split from",
  linkTask: "Link Task",
  unlink: "Unlink",
  resolveProblem: "Resolve Problem",
  notApplicable: "Not applicable",
  attach: "Attach image or file",
  comment: "Comment",
  completionEvidence: "Completion evidence",
  completionHint: "Completion is separate from Problem resolution and publication.",
  completionPlaceholder: "Describe the evidence supporting completion",
  createDraft: "Create draft",
  creatingDraft: "Creating private draft…",
  saveDraftBeforeQueueResult: "Save your current Knowledge draft edits before opening a Queue result.",
  draftQueued: "Private draft generation is queued. Open AI Queue to follow progress.",
  draftReady: "Private draft ready to review.",
  draftPreview: "Draft preview (Markdown)",
  draftPreviewHint: "Read this exact Markdown draft before editing or publishing.",
  editDraft: "Edit draft",
  saveDraftBeforePublish: "Save this correction before publishing.",
  savingDraft: "Saving draft correction…",
  draftSaved: "Draft correction saved. Review this version before publishing.",
  publishingDraft: "Publishing reviewed draft…",
  draftPublished: "Reviewed draft published.",
  knowledgeDraftBody: "Knowledge draft body",
  saveDraftCorrection: "Save draft correction",
  regenerateDraft: "Regenerate draft",
  withdrawKnowledge: "Withdraw Knowledge",
  flow: "Lineage",
  recordedWork: "Recorded work",
  close: "Close",
  send: "Send",
  conversation: "Conversation",
  optionalAssistance: "Optional assistance",
  asyncReview: "Async review",
  you: "You",
  assistant: "Assistant",
  refinementMessage: "Refinement message",
  refinementPlaceholder: "Ask the assistant to help organize this…",
  savedRefinementNote: "Saved refinement note",
  savedRefinementPlaceholder: "A private note saved with this refinement",
  proposedChange: "Review this proposed change.",
  assistantFailure: "The assistant could not finish. Your draft is still saved.",
  assistantGenerating: "Assistant is responding",
  edit: "Edit",
  apply: "Apply",
  reject: "Reject",
  loading: "Loading…",
  noActive: "No active Tasks yet.",
  noRefining: "Nothing is waiting for refinement.",
  draft: "Knowledge draft",
  publishHint: "Review this exact draft before publishing.",
  readinessItemsRemain: "readiness items remain",
  noExplicitPrerequisite: "No explicit prerequisite",
  readinessReason: "Reason",
  draftConflict: "This Task changed elsewhere. Keep your edits or use the latest version before saving.",
  keepMyEdits: "Keep my edits",
  useLatestVersion: "Use latest version",
  unsavedTaskChanges: "Unsaved Task changes",
  latestValue: "Latest saved value",
  editedValue: "Your edited value",
  savedRefreshFailed: "Changes saved, but the latest Task could not be loaded.",
  guardSave: "Save",
  saveBeforeClosing: "Save changes before leaving this Task?",
  discard: "Discard",
  keepEditing: "Keep editing",
  delete: "Delete",
  deleteItem: "Delete this item",
  deleteConfirm: "Delete this item from the Workbench?",
  deleteExplanation: "The item will be hidden from the Workbench. Linked Knowledge documents and vault files will be kept.",
  deleteCancel: "Keep item",
  deleteFailure: "The item could not be deleted.",
};
const ko: typeof en = {
  attachImage: "이미지 첨부",
  removeImage: "이미지 제거",
  imageHint: "이미지 붙여넣기 또는 파일 선택 · PNG, JPEG, GIF, WebP · 최대 10 MB",
  imageError: "10 MB 이하의 PNG, JPEG, GIF 또는 WebP 이미지를 선택해 주세요.",
  imageReadError: "이미지를 읽지 못했습니다. 다시 선택해 주세요.",
  imageCapture: "이미지 캡처",
  attachedImage: "첨부 이미지",
  refined: "Refined - Revision",
  workStatus: "작업 상태",
  previewTab: "프리뷰",
  focus: "진행 중인 작업에 Focus",
  showAllWork: "모든 작업 보기",
  subtask: "Subtask",
  subtasks: "Subtask 목록",
  parentTask: "Parent Task",
  siblingTasks: "Sibling Task",
  boundaryReason: "Subtask가 필요한 이유",
  boundaryContext: "Task 경계",
  autoPublishFailure: "자동 발행 대기 중입니다. Task를 다시 열면 재시도합니다",
  subtaskHint: "Subtask가 완료될 때마다 부모 Knowledge 리비전을 갱신·발행하고, 모든 Subtask가 완료되면 부모도 완료합니다.",
  workspace: "내 작업 공간",
  vaultStatus: "로컬 · 내 보관함",
  entryMode: "입력 방식",
  entryLabel: "작업대 입력",
  resume: "이어서 하기",
  ready: "Task",
  inProgress: "진행 중",
  completed: "완료",
  heading: "내 작업대",
  capture: "생각 남기기",
  task: "Task로 등록",
  placeholder: "남기거나 진행할 내용을 입력하세요",
  save: "저장",
  active: "진행 중인 Task",
  refining: "다듬는 중",
  categories: "모든 작업",
  inbox: "Inbox",
  inboxHint: "다시 살펴볼 생각을 모아두세요",
  noInbox: "생각을 남기면 여기에 모입니다.",
  refiningHint: "생각을 구체적인 작업으로 다듬으세요",
  refinedTasks: "정제된 Task",
  refinedTasksHint: "다음에 진행할 작업을 골라보세요",
  noReadyTasks: "등록하거나 다듬은 Task가 여기에 모입니다.",
  empty: "아직 항목이 없습니다. 생각을 남기거나 Task를 등록하세요.",
  retry: "다시 시도",
  open: "Task 열기",
  refine: "다듬기",
  worklog: "작업 기록",
  work: "작업",
  detailsTab: "세부 정보",
  reviewTab: "검토",
  worklogEntry: "작업 기록 항목",
  imageSummary: "AI 이미지 요약",
  summarizeImage: "이미지 요약 · 한글 + 영문",
  imageSummaryPending: "AI 작업 큐에서 한글·영문 요약을 생성하고 있습니다…",
  imageSummaryFailed: "이미지 요약이 완료되지 않았습니다. 여기나 AI 작업 큐에서 다시 시도하세요.",
  noWorkLog: "준비가 되면 첫 작업 기록을 남기세요.",
  goalMissing: "이 작업의 목표를 분명히 하려면 세부 정보에서 목표 결과를 추가하세요.",
  start: "작업 시작",
  complete: "Task 완료",
  addCompletionEvidence: "완료 근거 추가",
  reviewCompletion: "완료 검토",
  reopen: "다시 열기",
  readiness: "준비 상태",
  readinessOutcome: "목표 결과",
  readinessScope: "범위",
  readinessCriteria: "검증 기준",
  readinessPrerequisites: "선행 조건",
  statusResolved: "충족",
  statusMissing: "미충족",
  statusNotApplicable: "해당 없음",
  relationships: "연결",
  connectionDetails: "연결 상세",
  completion: "완료",
  knowledge: "Knowledge",
  review: "충돌 검토",
  runReview: "검토 실행",
  retryReview: "검토 다시 시도",
  cancel: "취소",
  currentReviewResult: "현재 결과",
  reviewClear: "문제 없음",
  reviewFindings: "검토 결과 있음",
  reviewInsufficient: "근거 부족",
  reviewQueued: "대기 중",
  reviewRunning: "검토 중",
  reviewFailed: "실패",
  reviewCancelled: "취소됨",
  reviewStale: "최신 상태 아님",
  reviewAttempts: "검토 시도",
  reviewAttempt: "시도",
  add: "추가",
  saveChanges: "변경 저장",
  nonblocking: "검토는 참고용입니다. 계속 작업할 수 있습니다.",
  proposals: "제안",
  previewContext: "관련 맥락",
  previewReturn: "프리뷰로 돌아가기",
  previewCategory: "분류",
  previewNote: "메모",
  previewTitle: "제안 결과",
  previewUnapplied: "프리뷰 · 적용 전",
  previewEmpty: "대화 후 제안 결과가 여기에 표시됩니다.",
  previewGenerating: "AI 작업 큐에서 프리뷰를 업데이트하는 중…",
  previewQueueRecovery: "프리뷰를 사용할 수 없습니다. AI 작업 큐에서 재시도하거나 새 메시지를 보내세요. 대화는 저장되어 있습니다.",
  previewNewTask: "이 항목 정제",
  splitTask: "하위 작업으로 분리",
  originalCapture: "처음 남긴 내용",
  previewTaskChange: "Task 변경",
  previewProblem: "Problem 변경",
  previewConnection: "Problem 연결",
  previewApplied: "적용했습니다. 현재 작업이 업데이트되었습니다.",
  previewRejected: "제안을 거절했습니다. 현재 작업을 유지합니다.",
  previewFinishEdit: "프리뷰 보기",
  closeRefinement: "다듬기 닫기",
  backToTask: "Task로 돌아가기",

  problem: "문제 맥락",
  publish: "승인한 초안 발행",
  taskDetails: "Task 세부 정보",
  closeTaskDetail: "Task 세부 정보 닫기",
  back: "작업대로 돌아가기",
  title: "제목",
  detail: "세부 내용",
  outcome: "목표 결과",
  scope: "범위",
  nonGoals: "하지 않을 일",
  criteria: "검증 기준",
  checklist: "체크리스트",
  checklistItem: "체크리스트 항목",
  showCompleted: "완료 항목 보기",
  showAllChecklist: "전체 항목 보기",
  collapseChecklist: "항목 접기",
  hideCompleted: "완료 항목 숨기기",
  decisions: "결정",
  decisionEntry: "결정",
  newProblemStatement: "새 Problem 설명",
  newProblemPlaceholder: "연결할 Problem을 설명하세요",
  createAndLinkProblem: "Problem 생성 및 연결",
  problemRevisionStatement: "Problem 개정 설명",
  problemRevisionPlaceholder: "연결된 Problem을 개정하세요",
  reviseProblem: "Problem 개정",
  problemId: "Problem ID",
  problemRevision: "Problem 개정 번호",
  linkProblem: "Problem 연결",
  relatedTaskId: "연결할 Task ID",
  taskId: "Task ID",
  relationshipKind: "관계 종류",
  related: "관련",
  prerequisite: "선행 조건",
  splitFrom: "분리됨",
  linkTask: "Task 연결",
  unlink: "연결 해제",
  resolveProblem: "Problem 해결 기록",
  notApplicable: "해당 없음",
  attach: "이미지 또는 파일 첨부",
  comment: "댓글",
  completionEvidence: "완료 근거",
  completionHint: "Task 완료, Problem 해결, Knowledge 발행은 서로 별개의 결정입니다.",
  completionPlaceholder: "완료를 뒷받침하는 근거를 설명하세요",
  createDraft: "초안 만들기",
  creatingDraft: "비공개 초안을 만드는 중…",
  saveDraftBeforeQueueResult: "큐 결과를 열기 전에 현재 Knowledge 초안의 수정 내용을 저장하세요.",
  draftQueued: "비공개 초안 생성을 Queue에 넣었습니다. AI Queue에서 진행 상황을 확인하세요.",
  draftReady: "비공개 초안이 준비되었습니다. 내용을 검토하세요.",
  draftPreview: "초안 미리보기 (Markdown)",
  draftPreviewHint: "수정하거나 발행하기 전에 Markdown 초안을 검토하세요.",
  editDraft: "초안 수정",
  saveDraftBeforePublish: "발행하기 전에 이 수정을 저장하세요.",
  savingDraft: "초안 수정을 저장하는 중…",
  draftSaved: "초안 수정이 저장되었습니다. 발행하기 전에 이 버전을 검토하세요.",
  publishingDraft: "검토한 초안을 발행하는 중…",
  draftPublished: "검토한 초안을 발행했습니다.",
  knowledgeDraftBody: "Knowledge 초안 본문",
  saveDraftCorrection: "초안 수정 저장",
  regenerateDraft: "초안 다시 생성",
  withdrawKnowledge: "Knowledge 철회",
  flow: "계보",
  recordedWork: "기록된 작업",
  close: "닫기",
  send: "보내기",
  conversation: "대화",
  optionalAssistance: "선택형 지원",
  asyncReview: "비동기 검토",
  you: "사용자",
  assistant: "도우미",
  refinementMessage: "다듬기 메시지",
  refinementPlaceholder: "도우미에게 정리를 요청하세요…",
  savedRefinementNote: "저장된 다듬기 메모",
  savedRefinementPlaceholder: "이 다듬기 세션에 저장되는 비공개 메모",
  proposedChange: "제안된 변경 사항을 검토하세요.",
  assistantFailure: "도우미가 작업을 마치지 못했습니다. 작성한 초안은 저장되어 있습니다.",
  assistantGenerating: "도우미가 응답하는 중",
  edit: "수정",
  apply: "적용",
  reject: "거절",
  loading: "불러오는 중…",
  noActive: "진행 중인 Task가 없습니다.",
  noRefining: "다듬기를 기다리는 항목이 없습니다.",
  draft: "Knowledge 초안",
  publishHint: "발행 전에 이 정확한 초안을 검토하세요.",
  readinessItemsRemain: "개의 준비 항목이 남았습니다",
  noExplicitPrerequisite: "명시된 선행 조건 없음",
  readinessReason: "사유",
  draftConflict: "다른 곳에서 이 Task가 변경되었습니다. 저장하기 전에 편집 내용을 유지하거나 최신 버전을 사용하세요.",
  keepMyEdits: "내 편집 내용 유지",
  useLatestVersion: "최신 버전 사용",
  unsavedTaskChanges: "저장하지 않은 Task 변경 사항",
  latestValue: "최근 저장된 값",
  editedValue: "편집한 값",
  savedRefreshFailed: "변경 사항을 저장했지만 최신 Task를 불러오지 못했습니다.",
  guardSave: "저장",
  saveBeforeClosing: "이 Task를 떠나기 전에 변경 사항을 저장할까요?",
  discard: "버리기",
  keepEditing: "계속 편집",
  delete: "삭제",
  deleteItem: "이 항목 삭제",
  deleteConfirm: "이 항목을 작업대에서 삭제할까요?",
  deleteExplanation: "항목이 작업대에서 숨겨집니다. 연결된 Knowledge 문서와 보관함 파일은 유지됩니다.",
  deleteCancel: "항목 유지",
  deleteFailure: "항목을 삭제하지 못했습니다.",
};
const subscribe = (changed: () => void) => {
  const observer = new MutationObserver(changed);
  observer.observe(document.documentElement, {
    attributes: true,
    attributeFilter: ["lang"],
  });
  return () => observer.disconnect();
};
export const useTaskWorkbenchText = () =>
  useSyncExternalStore(
    subscribe,
    () => (document.documentElement.lang.startsWith("ko") ? ko : en),
    () => en,
  );
