import { useSyncExternalStore } from "react";

const en = {
  workspace: "Local workspace",
  vaultStatus: "Local · your vault",
  entryMode: "Entry mode",
  entryLabel: "Workbench entry",
  resume: "Resume",
  ready: "Task",
  inProgress: "In progress",
  completed: "Completed",
  heading: "Your workbench",
  capture: "Capture a thought",
  task: "Register as a Task",
  placeholder: "What would you like to keep or work on?",
  save: "Save",
  active: "Active tasks",
  refining: "Refining",
  categories: "All work",
  empty: "Nothing here yet. Capture a thought or register a Task.",
  retry: "Try again",
  open: "Open Task",
  refine: "Refine",
  worklog: "Work Log",
  worklogEntry: "Work Log entry",
  start: "Start work",
  complete: "Complete Task",
  reopen: "Reopen Task",
  readiness: "Readiness",
  readinessOutcome: "Outcome",
  readinessScope: "Scope",
  readinessCriteria: "Validation criteria",
  readinessPrerequisites: "Prerequisites",
  statusResolved: "Resolved",
  statusMissing: "Missing",
  statusNotApplicable: "Not applicable",
  relationships: "Connections",
  connectionDetails: "Connection details",
  completion: "Completion",
  knowledge: "Knowledge",
  review: "Conflict review",
  runReview: "Run review",
  retryReview: "Retry review",
  cancel: "Cancel",
  currentReviewResult: "Current result",
  reviewClear: "Clear",
  reviewFindings: "Findings",
  reviewInsufficient: "Insufficient evidence",
  reviewQueued: "Queued",
  reviewRunning: "Running",
  reviewFailed: "Failed",
  reviewCancelled: "Cancelled",
  reviewStale: "Stale",
  reviewAttempts: "Review attempts",
  reviewAttempt: "Attempt",
  add: "Add",
  saveChanges: "Save changes",
  nonblocking: "Review is advisory. You can continue working.",
  proposals: "Proposals",
  problem: "Problem context",
  publish: "Publish approved draft",
  taskDetails: "Task details",
  closeTaskDetail: "Close Task detail",
  title: "Title",
  detail: "Detail",
  outcome: "Outcome",
  scope: "Scope",
  nonGoals: "Non-goals",
  criteria: "Validation criteria",
  checklist: "Checklist",
  checklistItem: "Checklist item",
  decisions: "Decisions",
  decisionEntry: "Decision",
  newProblemStatement: "New Problem statement",
  newProblemPlaceholder: "Describe a Problem to link",
  createAndLinkProblem: "Create and link Problem",
  problemRevisionStatement: "Problem revision statement",
  problemRevisionPlaceholder: "Revise the linked Problem",
  reviseProblem: "Revise Problem",
  problemId: "Problem ID",
  problemRevision: "Problem revision",
  linkProblem: "Link Problem",
  relatedTaskId: "Related Task ID",
  taskId: "Task ID",
  relationshipKind: "Relationship kind",
  related: "Related",
  prerequisite: "Prerequisite",
  splitFrom: "Split from",
  linkTask: "Link Task",
  unlink: "Unlink",
  resolveProblem: "Resolve Problem",
  notApplicable: "Not applicable",
  attach: "Attach image or file",
  comment: "Comment",
  completionEvidence: "Completion evidence",
  completionHint: "Completion is separate from Problem resolution and publication.",
  completionPlaceholder: "Describe the evidence supporting completion",
  createDraft: "Create draft",
  knowledgeDraftBody: "Knowledge draft body",
  saveDraftCorrection: "Save draft correction",
  regenerateDraft: "Regenerate draft",
  withdrawKnowledge: "Withdraw Knowledge",
  flow: "Lineage",
  recordedWork: "Recorded work",
  close: "Close",
  send: "Send",
  conversation: "Conversation",
  optionalAssistance: "Optional assistance",
  asyncReview: "Async review",
  you: "You",
  assistant: "Assistant",
  refinementMessage: "Refinement message",
  refinementPlaceholder: "Ask the assistant to help organize this…",
  savedRefinementNote: "Saved refinement note",
  savedRefinementPlaceholder: "A private note saved with this refinement",
  proposedChange: "Review this proposed change.",
  assistantFailure: "The assistant could not finish. Your draft is still saved.",
  edit: "Edit",
  apply: "Apply",
  reject: "Reject",
  loading: "Loading…",
  noActive: "No active Tasks yet.",
  noRefining: "Nothing is waiting for refinement.",
  draft: "Knowledge draft",
  publishHint: "Review this exact draft before publishing.",
  readinessItemsRemain: "readiness items remain",
};
const ko: typeof en = {
  workspace: "내 작업 공간",
  vaultStatus: "로컬 · 내 보관함",
  entryMode: "입력 방식",
  entryLabel: "작업대 입력",
  resume: "이어서 하기",
  ready: "Task",
  inProgress: "진행 중",
  completed: "완료",
  heading: "내 작업대",
  capture: "생각 남기기",
  task: "Task로 등록",
  placeholder: "남기거나 진행할 내용을 입력하세요",
  save: "저장",
  active: "진행 중인 Task",
  refining: "다듬는 중",
  categories: "모든 작업",
  empty: "아직 항목이 없습니다. 생각을 남기거나 Task를 등록하세요.",
  retry: "다시 시도",
  open: "Task 열기",
  refine: "다듬기",
  worklog: "작업 기록",
  worklogEntry: "작업 기록 항목",
  start: "작업 시작",
  complete: "Task 완료",
  reopen: "다시 열기",
  readiness: "준비 상태",
  readinessOutcome: "목표 결과",
  readinessScope: "범위",
  readinessCriteria: "검증 기준",
  readinessPrerequisites: "선행 조건",
  statusResolved: "충족",
  statusMissing: "미충족",
  statusNotApplicable: "해당 없음",
  relationships: "연결",
  connectionDetails: "연결 상세",
  completion: "완료",
  knowledge: "Knowledge",
  review: "충돌 검토",
  runReview: "검토 실행",
  retryReview: "검토 다시 시도",
  cancel: "취소",
  currentReviewResult: "현재 결과",
  reviewClear: "문제 없음",
  reviewFindings: "검토 결과 있음",
  reviewInsufficient: "근거 부족",
  reviewQueued: "대기 중",
  reviewRunning: "검토 중",
  reviewFailed: "실패",
  reviewCancelled: "취소됨",
  reviewStale: "최신 상태 아님",
  reviewAttempts: "검토 시도",
  reviewAttempt: "시도",
  add: "추가",
  saveChanges: "변경 저장",
  nonblocking: "검토는 참고용입니다. 계속 작업할 수 있습니다.",
  proposals: "제안",
  problem: "문제 맥락",
  publish: "승인한 초안 발행",
  taskDetails: "Task 세부 정보",
  closeTaskDetail: "Task 세부 정보 닫기",
  title: "제목",
  detail: "세부 내용",
  outcome: "목표 결과",
  scope: "범위",
  nonGoals: "하지 않을 일",
  criteria: "검증 기준",
  checklist: "체크리스트",
  checklistItem: "체크리스트 항목",
  decisions: "결정",
  decisionEntry: "결정",
  newProblemStatement: "새 Problem 설명",
  newProblemPlaceholder: "연결할 Problem을 설명하세요",
  createAndLinkProblem: "Problem 생성 및 연결",
  problemRevisionStatement: "Problem 개정 설명",
  problemRevisionPlaceholder: "연결된 Problem을 개정하세요",
  reviseProblem: "Problem 개정",
  problemId: "Problem ID",
  problemRevision: "Problem 개정 번호",
  linkProblem: "Problem 연결",
  relatedTaskId: "연결할 Task ID",
  taskId: "Task ID",
  relationshipKind: "관계 종류",
  related: "관련",
  prerequisite: "선행 조건",
  splitFrom: "분리됨",
  linkTask: "Task 연결",
  unlink: "연결 해제",
  resolveProblem: "Problem 해결 기록",
  notApplicable: "해당 없음",
  attach: "이미지 또는 파일 첨부",
  comment: "댓글",
  completionEvidence: "완료 근거",
  completionHint: "Task 완료, Problem 해결, Knowledge 발행은 서로 별개의 결정입니다.",
  completionPlaceholder: "완료를 뒷받침하는 근거를 설명하세요",
  createDraft: "초안 만들기",
  knowledgeDraftBody: "Knowledge 초안 본문",
  saveDraftCorrection: "초안 수정 저장",
  regenerateDraft: "초안 다시 생성",
  withdrawKnowledge: "Knowledge 철회",
  flow: "계보",
  recordedWork: "기록된 작업",
  close: "닫기",
  send: "보내기",
  conversation: "대화",
  optionalAssistance: "선택형 지원",
  asyncReview: "비동기 검토",
  you: "사용자",
  assistant: "도우미",
  refinementMessage: "다듬기 메시지",
  refinementPlaceholder: "도우미에게 정리를 요청하세요…",
  savedRefinementNote: "저장된 다듬기 메모",
  savedRefinementPlaceholder: "이 다듬기 세션에 저장되는 비공개 메모",
  proposedChange: "제안된 변경 사항을 검토하세요.",
  assistantFailure: "도우미가 작업을 마치지 못했습니다. 작성한 초안은 저장되어 있습니다.",
  edit: "수정",
  apply: "적용",
  reject: "거절",
  loading: "불러오는 중…",
  noActive: "진행 중인 Task가 없습니다.",
  noRefining: "다듬기를 기다리는 항목이 없습니다.",
  draft: "Knowledge 초안",
  publishHint: "발행 전에 이 정확한 초안을 검토하세요.",
  readinessItemsRemain: "개의 준비 항목이 남았습니다",
};
const subscribe = (changed: () => void) => {
  const observer = new MutationObserver(changed);
  observer.observe(document.documentElement, {
    attributes: true,
    attributeFilter: ["lang"],
  });
  return () => observer.disconnect();
};
export const useTaskWorkbenchText = () =>
  useSyncExternalStore(
    subscribe,
    () => (document.documentElement.lang.startsWith("ko") ? ko : en),
    () => en,
  );
