use super::super::{definition, versioned_definition, OperationKind, PromptDefinition, PromptId};

const DISTILLATION_CONTRACT: &str = r#"Return exactly one JSON object with this complete shape (empty arrays are valid):
{"claims":[{"id":"claim-key","kind":"goal|scope|criterion|decision|result|evidence|attempt|idea|completion","statement":"exact supported statement","actor":"user|ai|tool","epistemicState":"suggested|decided|attempted|performed|observed|verified","status":"current|contradicted|historical|unknown","topicKey":null,"sources":[{"type":"source type","id":"source id","revision":"source revision","locator":"exact locator","quote":"verbatim non-empty source substring"}],"contradictedBy":[]}],"nodeChanges":[{"action":"add|enrich|merge|omit|supersede","candidateId":"temporary model-local id","targetIds":[],"expectedTargetRevisions":{},"claimIds":["claim-key"],"detail":{"before":null,"after":null,"reason":null,"evidenceClaimIds":[],"result":null,"currentStatus":"unresolved","links":[]},"sources":[]}],"relationshipChanges":[{"id":"relationship-key","kind":"supports|verifies|contradicts|supersedes|merged_into","from":"node id","to":"node id","reason":null,"sources":[]}],"topicStates":[{"topicKey":"topic","status":"adopted|superseded|withdrawn|unresolved","currentNodeId":null,"replacementNodeId":null,"sources":[]}],"completionSnapshots":[{"id":"snapshot-key","completionId":"exact completion source id","completionRevision":"exact completion source revision","status":"current|historical_after_reopen|superseded_by_later_completion","claimIds":[],"unresolved":[],"verificationState":"recorded|partially_verified|verified","sources":[]}],"workLogView":{"sections":[{"kind":"outcome|decisions|evidence|unresolved","claimIds":[]}]},"warnings":[],"dependencies":[{"source":{"type":"source type","id":"source id","revision":"source revision","locator":"exact locator","quote":"verbatim non-empty source substring"},"claimIds":[],"relationshipIds":[]}]}.
Treat the supplied final report as primary; use completed evidence only for material corroboration, omissions, or contradictions. Every citation must copy a non-empty exact quote from the supplied source at its exact type/id/revision/locator. Existing semantic graph nodes include the only valid target IDs and revisions for enrich, merge, and supersede; include an expectedTargetRevisions entry for every target. Distinguish suggested, decided, attempted, performed, observed, and verified. Use verified only when a successful_check source states that exact claim; use decided/adopted only from an explicit_decision; create a completion snapshot only from its matching explicit_completion. Retain every failed_check as an exact observed failure claim or a contradictedBy binding to the same command subject (topicKey equals source.subject). A failed_approach is historical failed work followed by a successful retry, not evidence against unrelated work. Never omit known failed evidence. An observed_exit only records process exit; it never verifies correctness. For decided, statement and quote must equal the full explicit decision source (including its context) so negation cannot be dropped. For verified, statement and quote must equal the complete successful_check evidence, not a polarity-changing substring. Completion claims must quote their matching canonical completion; recorded completion never verifies all work. Supersession requires a matching explicit decision and verbatim supported reason. Prefer enrich for materially continuing the same work, preserving the existing target ID; never use add to overwrite an existing node. Never infer adoption, verification, reason, finality, or causality from chronology. Omit routine retry, continue, reconnect, and approval controls. Preserve unknown values as unresolved. Do not change Task or publication state."#;

static DEFINITIONS: [PromptDefinition; 7] = [
    definition(PromptId::CaptureDistillation, OperationKind::CaptureDistillation, &["schemaVersion", "title", "content", "context", "explicitRequests", "grounding"], "Organize the supplied initial Capture without changing its raw text or images. Return JSON only with schemaVersion 1, title (at most 120 characters), content (at most 4000 characters), context (at most 2000 characters), explicitRequests (at most 8 strings of 500 characters), and grounding. Keep context and requests empty when unsupported. grounding is an array of {field,sourceRefs}; every nonempty semantic field and explicitRequests.N entry must cite one or more supplied text:start-end or image:N references. Do not infer unseen image text, workflow state, Tasks, Problems, completion, adoption, or publication."),
    versioned_definition(PromptId::WorkLogDistillation, 3, OperationKind::WorkLogDistillation, &["claims", "nodeChanges", "relationshipChanges", "topicStates", "completionSnapshots", "workLogView", "warnings", "dependencies"], DISTILLATION_CONTRACT),
    versioned_definition(PromptId::RunReportDistillation, 3, OperationKind::RunReportDistillation, &["claims", "nodeChanges", "relationshipChanges", "topicStates", "completionSnapshots", "workLogView", "warnings", "dependencies"], DISTILLATION_CONTRACT),
    definition(PromptId::PublicationIndex, OperationKind::PublicationIndex, &["entries"], "Build index metadata only from the supplied published Knowledge revision."),
    definition(PromptId::SpeculativeSearch, OperationKind::SpeculativeSearch, &["results"], "Return optional search suggestions from supplied evidence without durable workflow changes."),
    definition(PromptId::UserGeneration, OperationKind::UserGeneration, &["proposal"], "Return a reviewable user-requested proposal. Never apply it automatically."),
    versioned_definition(PromptId::TaskJourneyIncrement, 3, OperationKind::TaskJourneyIncrement, &["claims", "nodeChanges", "relationshipChanges", "topicStates", "completionSnapshots", "workLogView", "warnings", "dependencies"], "Apply the supplied validated Distillation result to only the affected Task semantic subgraph. Preserve stable semantic IDs, original recorded events, immutable completion snapshots, and explicit decision history. Every citation retains its exact source quote and locator. Cite each add, enrich, merge, omit, or supersede action and relationship. Chronology alone never proves causality, adoption, verification, finality, or supersession."),
];

pub fn prompt_definition(id: PromptId) -> &'static PromptDefinition {
    let index = match id {
        PromptId::CaptureDistillation => 0,
        PromptId::WorkLogDistillation => 1,
        PromptId::RunReportDistillation => 2,
        PromptId::PublicationIndex => 3,
        PromptId::SpeculativeSearch => 4,
        PromptId::UserGeneration => 5,
        PromptId::TaskJourneyIncrement => 6,
        _ => unreachable!("current prompt routed to foundation registry"),
    };
    &DEFINITIONS[index]
}
