import {
  copyFileSync,
  existsSync,
  mkdirSync,
  readFileSync,
  readdirSync,
  unlinkSync,
  writeFileSync,
} from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const repositoryRoot = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const outputRoot = join(repositoryRoot, 'frontend', 'public', 'assets');
const fontOutput = join(outputRoot, 'fonts');
const fontSources = [
  ['@fontsource/dm-mono', '400.css'],
  ['@fontsource/dm-mono', '500.css'],
  ['@fontsource/nunito', '500.css'],
  ['@fontsource/nunito', '600.css'],
  ['@fontsource/nunito', '700.css'],
  ['@fontsource/nunito', '800.css'],
  ['@fontsource-variable/noto-sans-kr', 'index.css'],
];

mkdirSync(fontOutput, { recursive: true });

const emittedFiles = new Set();
const styles = fontSources.map(([packageName, cssFile]) => {
  const packageRoot = join(repositoryRoot, 'node_modules', packageName);
  const source = readFileSync(join(packageRoot, cssFile), 'utf8');
  const woff2Only = source.replace(
    /src: url\((\.\/files\/[^)]+\.woff2)\) format\('woff2(?:-variations)?'\), url\(\.\/files\/[^)]+\.woff\) format\('woff'\);/g,
    (_match, woff2Path) => `src: url(${woff2Path}) format('woff2');`,
  );

  return woff2Only.replace(/url\(\.\/files\/([^)]+\.woff2)\)/g, (_match, fileName) => {
    const sourceFile = join(packageRoot, 'files', fileName);
    if (!existsSync(sourceFile)) {
      throw new Error(`Bundled font source is missing: ${sourceFile}`);
    }
    copyFileSync(sourceFile, join(fontOutput, fileName));
    emittedFiles.add(fileName);
    return `url('./fonts/${fileName}')`;
  });
});

for (const existingFile of readdirSync(fontOutput)) {
  if (!emittedFiles.has(existingFile)) {
    unlinkSync(join(fontOutput, existingFile));
  }
}

const banner = `/* Generated by scripts/prepare_fonts.mjs.
 * Nunito, DM Mono, and Noto Sans KR are bundled under the SIL Open Font License 1.1.
 */\n`;
writeFileSync(join(outputRoot, 'fonts.css'), `${banner}${styles.join('\n')}\n`);
console.log(`bundled ${emittedFiles.size} WOFF2 font subsets`);
